### ISSUE TITLE
gdistsamp error with time as detection cov

### ISSUE THREAD

**Issue by kfpbennett** [bsevansunc/birdCats#6]
I may have gotten gdistsamp working, since I can run the models and still look at the unmarkedframeGDS (which was the issue before). However, when I try to include time as a detection covariate, I get the following error:

Error in optim(starts, nll, method = method, hessian = se, ...) : 
  non-finite finite-difference value [4]

I tried supplying starting values, but it was not working. I may not have been supplying close enough values, though?

**Comment by bsevansunc** [comment]
It appears that times are provided as character values rather than integer. This would force the model to assess the variable as a factor (and therefore you would be estimating for each time unit as factor level -- not what you want). It would be better to convert the time to minutes-since-midnight.

Also, the code, as written, puts out an error in transpose covariates and sitesWithCovs (object dew not found). I woud imagine that this is because you have done something in the Console that didn't make it to the script (or have an object stored in your environment that isn't scripted).

**Comment by bsevansunc** [comment]
An example of how to get minutes-since-midnight with a character vector of times:

time <- c('08:15', '14:32', '7:12')

stringr::str_split_fixed(time, ':', 2) %>%
  data.frame %>%
  dplyr::rename(hour = X1, minute = X2) %>%
  dplyr::mutate_each('as.numeric') %>%
  dplyr::mutate(minutesSinceMidnight = hour*60 + minute)

**Comment by kfpbennett** [comment]
I have been going over this and can't seem to understand the issues you brought up. I had previously converted time to a 'minutes since midnight' format, and mine puts out no errors in the function, etc. I checked through every relevant file, and all seem to be updated on GitHub (including the updated time, dew, etc.)
